name: deep_proj
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipython
  - ipython_genutils
  - matplotlib
  - matplotlib-base
  - notebook
  - numpy
  - pandas
  - pillow
  - pip
  - plotly
  - python=3.9.13
  - scikit-learn
  - scipy=1.5.2
  - seaborn
  - tornado
  - tqdm
  - transformers==4.29.2

  - pip:
    - optuna
    - opencv-python==3.4.16.57
